# Generated by Django 5.0.14 on 2025-06-19 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('iddia', models.AutoField(primary_key=True, serialize=False)),
                ('nombredia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Dia',
            },
        ),
        migrations.CreateModel(
            name='Disponibilidadcurso',
            fields=[
                ('iddisponibilidadcurso', models.AutoField(primary_key=True, serialize=False)),
                ('disponibilidad', models.BooleanField()),
            ],
            options={
                'db_table': 'DisponibilidadCurso',
            },
        ),
        migrations.CreateModel(
            name='Disponibilidadhorario',
            fields=[
                ('iddisponibilidadhorario', models.AutoField(primary_key=True, serialize=False)),
                ('disponibilidad', models.BooleanField()),
            ],
            options={
                'db_table': 'DisponibilidadHorario',
            },
        ),
        migrations.CreateModel(
            name='Disponibilidadsalon',
            fields=[
                ('iddisponibilidadsalon', models.AutoField(primary_key=True, serialize=False)),
                ('disponibilidad', models.BooleanField()),
            ],
            options={
                'db_table': 'DisponibilidadSalon',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('idestudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidopaterno', models.CharField(max_length=100)),
                ('apellidomaterno', models.CharField(max_length=100)),
                ('telefonoestudiante', models.CharField(max_length=15)),
                ('fechanacimiento', models.DateField()),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('idprofesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidopaterno', models.CharField(max_length=100)),
                ('apellidomaterno', models.CharField(max_length=100)),
                ('telefonoprofesor', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idhorario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('horainicio', models.TimeField()),
                ('horafin', models.TimeField()),
                ('iddia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.dia')),
                ('iddisponibilidadhorario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.disponibilidadhorario')),
            ],
            options={
                'db_table': 'Horario',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('idcurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iddisponibilidadcurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.disponibilidadcurso')),
                ('idprofesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.profesores')),
            ],
            options={
                'db_table': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Ordenparticionada',
            fields=[
                ('idorden', models.IntegerField()),
                ('fechaorden', models.DateField()),
                ('idestudiante', models.IntegerField(blank=True, null=True)),
                ('idcurso', models.IntegerField(blank=True, null=True)),
                ('idsalon', models.IntegerField(blank=True, null=True)),
                ('idhorario', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('anio', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'OrdenParticionada',
                'unique_together': {('anio', 'idorden')},
            },
        ),
        migrations.CreateModel(
            name='Salones',
            fields=[
                ('idsalon', models.AutoField(primary_key=True, serialize=False)),
                ('codigosalon', models.CharField(max_length=50)),
                ('aforosalon', models.IntegerField()),
                ('iddisponibilidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.disponibilidadsalon')),
            ],
            options={
                'db_table': 'Salones',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('idorden', models.AutoField(primary_key=True, serialize=False)),
                ('fechaorden', models.DateField()),
                ('estado', models.BooleanField()),
                ('idcurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.cursos')),
                ('idestudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.estudiantes')),
                ('idhorario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.horario')),
                ('idsalon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.salones')),
            ],
            options={
                'db_table': 'Orden',
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'unique_together': {('principal_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Solicita',
            fields=[
                ('idestudiante', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.estudiantes')),
                ('idcurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.cursos')),
            ],
            options={
                'db_table': 'Solicita',
                'unique_together': {('idestudiante', 'idcurso')},
            },
        ),
        migrations.CreateModel(
            name='Imparte',
            fields=[
                ('idprofesor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.profesores')),
                ('idcurso', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.cursos')),
            ],
            options={
                'db_table': 'Imparte',
                'unique_together': {('idprofesor', 'idcurso')},
            },
        ),
    ]
